const fs=require("fs")
// console.log(fs);
///MKDIR
//recursive: false
//دقیق یادم نیست ولی اگه ترو بود و ما اون فولدری که می خواستیم بسازیم موجود بود مشکلی نداشت و اروری به ما نمیداد ولی اگه فالس بود به ما ارور میداد که این فولدر قبلا وجود دارد

// fs.mkdir("dog", { recursive: false },(err)=>{
// console.log(fs);
//  if (err) {
//     throw err;
//   }
// });
// fs.mkdirSync("Cats");

// const folder = process.argv[2] || "prject";
// try{
// fs.mkdirSync(folder)
// fs.writeFileSync(`${folder}/index.html`,"<html></html>")
// fs.writeFileSync(`${folder}/index.css`,"hi am css")
// fs.writeFileSync(`${folder}/index.js`, "hi am js");


// // console.log(folder);
// }
// catch(error){
//     console.log(error);
// }
